admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

service:
  type: NodePort
  nodePort: 30081

persistence:
  enabled: true
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  size: 5Gi
