apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: storefront
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - name: http-metrics
      port: 8081
      targetPort: 8081
